version: '2'
services:
  db:
    image: postgres
  cache:
    image: memcached
    ports:
      - "11211:11211"
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ${PWD}:/code
      - ${PWD}/hosts:/etc/hosts:ro
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache
  proxy:
    image: nginx
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/nginx/favicon.ico:/etc/nginx/favicon.ico
      - ${PWD}/nginx/mockatron.conf:/etc/nginx/mockatron.conf
      - ${PWD}/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "8001:8001"
      - "7080:7080"
      - "8080:8080"
    depends_on:
      - web
