version: '2'
services:
  db:
    image: postgres
  cache:
    image: memcached
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ${PWD}:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache
